# Railway deployment - No system dependencies needed
# Uses PyPDF2 for PDF processing (pure Python)

[variables]
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"

[start]
cmd = "python start_server.py"
