# Railway deployment configuration with C++ build support
[phases.setup]
nixPkgs = [
  "python311", 
  "pip", 
  "gcc", 
  "gxx", 
  "pkg-config", 
  "cmake", 
  "make"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir --prefer-binary --only-binary=:all: -r requirements.railway.txt || pip install --no-cache-dir -r requirements.railway.txt"
]

[variables]
# Build configuration
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
# Force binary installations where possible
PIP_PREFER_BINARY = "1"
# Environment variables for compilation if needed
CC = "gcc"
CXX = "g++"

[start]
cmd = "python start_server.py"
